### ISSUE TITLE
Store list as tsv files

### ISSUE THREAD

**Issue by sebdanielsson** [2004content/rarbg#8]
Storing the hash and display name of the magnet links in .tsv files would greatly improve the workflow of importing and analyzing this dataset. It would also allow for easier imports to various databases so that we can search through the links with ease. What do you think?

**Comment by 2004content** [comment]
i'm happy for anyone to reformat this stuff however they want for their use
or others', but i wanna keep mine the way it is.

**Comment by sebdanielsson** [comment]
Okay thanks👍
