### ISSUE TITLE
how do i start

### ISSUE THREAD

**Issue by blecaplol** [2004content/rarbg#9]
please help!

**Comment by fabianosrc** [comment]
Open the txt file, search for the file you want download, copy the magnet link and paste in your torrent client.

**Comment by campones** [comment]
ex you look for The Last Boy Scout (1991)
ctrl+f  in notepad++ with the rarbg movie text file, replace with dots The.Last.Boy.Scout.1991 
take the magnet 
magnet:?xt=urn:btih:8a196c04106e912da353a12ba143b16380e81c9e&dn=The.Last.Boy.Scout.1991.1080p.BluRay.x265-RARBG

that's it

**Comment by crushedoreos** [comment]
and what do the files in the everything folder do?

**Comment by blecaplol** [comment]
ty guys!
